<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Karyawan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Karyawan_model');
    } 

    /*
     * Listing of karyawan
     */
    function index()
    {
        $data['karyawan'] = $this->Karyawan_model->get_all_karyawan();
        $data['data'] = ['title'=>'Karyawan', 'header'=>'Karyawan'];
        $data['_view'] = 'karyawan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new karyawan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama' => $this->input->post('nama')
            );
            
            $karyawan_id = $this->Karyawan_model->add_karyawan($params);
            redirect('karyawan/index');
        }
        else
        {            
            $data['data'] = ['title'=>'Add Karyawan', 'header'=>'Add Karyawan'];
            $data['_view'] = 'karyawan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a karyawan
     */
    function edit($idkaryawan)
    {   
        // check if the karyawan exists before trying to edit it
        $data['karyawan'] = $this->Karyawan_model->get_karyawan($idkaryawan);
        
        if(isset($data['karyawan']['idkaryawan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama' => $this->input->post('nama')
                );

                $this->Karyawan_model->update_karyawan($idkaryawan,$params);            
                redirect('karyawan/index');
            }
            else
            {
                $data['_view'] = 'karyawan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The karyawan you are trying to edit does not exist.');
    } 

    /*
     * Deleting karyawan
     */
    function remove($idkaryawan)
    {
        $karyawan = $this->Karyawan_model->get_karyawan($idkaryawan);

        // check if the karyawan exists before trying to delete it
        if(isset($karyawan['idkaryawan']))
        {
            $this->Karyawan_model->delete_karyawan($idkaryawan);
            redirect('karyawan/index');
        }
        else
            show_error('The karyawan you are trying to delete does not exist.');
    }
    
}
