<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class User extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    }

    /*
     * Listing of user
     */
    public function index()
    {
        $data['user'] = $this->User_model->get_all_user();
        $data['data'] = ['title' => 'User', 'header' => 'User'];
        $data['_view'] = 'user/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new user
     */
    public function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'username' => $this->input->post('username'),
                'paddword' => $this->input->post('paddword'),
            );

            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        } else {
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a user
     */
    public function edit($iduser)
    {
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($iduser);

        if (isset($data['user']['iduser'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'username' => $this->input->post('username'),
                    'paddword' => $this->input->post('paddword'),
                );

                $this->User_model->update_user($iduser, $params);
                redirect('user/index');
            } else {
                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main', $data);
            }
        } else {
            show_error('The user you are trying to edit does not exist.');
        }

    }

    /*
     * Deleting user
     */
    public function remove($iduser)
    {
        $user = $this->User_model->get_user($iduser);

        // check if the user exists before trying to delete it
        if (isset($user['iduser'])) {
            $this->User_model->delete_user($iduser);
            redirect('user/index');
        } else {
            show_error('The user you are trying to delete does not exist.');
        }

    }

}
