<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Userinrole extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Userinrole_model');
    } 

    /*
     * Listing of userinrole
     */
    function index()
    {
        $data['userinrole'] = $this->Userinrole_model->get_all_userinrole();
        
        $data['_view'] = 'userinrole/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new userinrole
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'iduser' => $this->input->post('iduser'),
				'idrole' => $this->input->post('idrole'),
            );
            
            $userinrole_id = $this->Userinrole_model->add_userinrole($params);
            redirect('userinrole/index');
        }
        else
        {            
            $data['_view'] = 'userinrole/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a userinrole
     */
    function edit($iduserinrole)
    {   
        // check if the userinrole exists before trying to edit it
        $data['userinrole'] = $this->Userinrole_model->get_userinrole($iduserinrole);
        
        if(isset($data['userinrole']['iduserinrole']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'iduser' => $this->input->post('iduser'),
					'idrole' => $this->input->post('idrole'),
                );

                $this->Userinrole_model->update_userinrole($iduserinrole,$params);            
                redirect('userinrole/index');
            }
            else
            {
                $data['_view'] = 'userinrole/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The userinrole you are trying to edit does not exist.');
    } 

    /*
     * Deleting userinrole
     */
    function remove($iduserinrole)
    {
        $userinrole = $this->Userinrole_model->get_userinrole($iduserinrole);

        // check if the userinrole exists before trying to delete it
        if(isset($userinrole['iduserinrole']))
        {
            $this->Userinrole_model->delete_userinrole($iduserinrole);
            redirect('userinrole/index');
        }
        else
            show_error('The userinrole you are trying to delete does not exist.');
    }
    
}
