<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bobotkriterium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bobotkriterium by idbobotkriteria
     */
    function get_bobotkriterium($idperiode)
    {
        return $this->db->get_where('bobotkriteria',array('idperiode'=>$idperiode))->result_array();
    }
        
    /*
     * Get all bobotkriteria
     */
    function get_all_bobotkriteria()
    {
        $this->db->order_by('idbobotkriteria', 'asc');
        return $this->db->get('bobotkriteria')->result_array();
    }
        
    /*
     * function to add new bobotkriterium
     */
    function add_bobotkriterium($params)
    {
        $this->db->insert('bobotkriteria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bobotkriterium
     */
    function update_bobotkriterium($idbobotkriteria,$params)
    {
        $this->db->where('idbobotkriteria',$idbobotkriteria);
        return $this->db->update('bobotkriteria',$params);
    }
    
    /*
     * function to delete bobotkriterium
     */
    function delete_bobotkriterium($idbobotkriteria)
    {
        return $this->db->delete('bobotkriteria',array('idbobotkriteria'=>$idbobotkriteria));
    }
}
