<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Karyawan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get karyawan by idkaryawan
     */
    function get_karyawan($idkaryawan)
    {
        return $this->db->get_where('karyawan',array('idkaryawan'=>$idkaryawan))->row_array();
    }
        
    /*
     * Get all karyawan
     */
    function get_all_karyawan()
    {
        $this->db->order_by('idkaryawan', 'desc');
        return $this->db->get('karyawan')->result_array();
    }
        
    /*
     * function to add new karyawan
     */
    function add_karyawan($params)
    {
        $this->db->insert('karyawan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update karyawan
     */
    function update_karyawan($idkaryawan,$params)
    {
        $this->db->where('idkaryawan',$idkaryawan);
        return $this->db->update('karyawan',$params);
    }
    
    /*
     * function to delete karyawan
     */
    function delete_karyawan($idkaryawan)
    {
        return $this->db->delete('karyawan',array('idkaryawan'=>$idkaryawan));
    }
}
