<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pembobotan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pembobotan by idpembobotan
     */
    function get_pembobotan($idpembobotan)
    {
        return $this->db->get_where('pembobotan',array('idpembobotan'=>$idpembobotan))->row_array();
    }
        
    /*
     * Get all pembobotan
     */
    function get_all_pembobotan()
    {
        $this->db->order_by('idpembobotan', 'desc');
        return $this->db->get('pembobotan')->result_array();
    }
        
    /*
     * function to add new pembobotan
     */
    function add_pembobotan($params)
    {
        $this->db->insert('pembobotan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pembobotan
     */
    function update_pembobotan($idpembobotan,$params)
    {
        $this->db->where('idpembobotan',$idpembobotan);
        return $this->db->update('pembobotan',$params);
    }
    
    /*
     * function to delete pembobotan
     */
    function delete_pembobotan($idpembobotan)
    {
        return $this->db->delete('pembobotan',array('idpembobotan'=>$idpembobotan));
    }
}
