<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Periode_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get periode by idperiode
     */
    function get_periode($idperiode)
    {
        return $this->db->get_where('periode',array('idperiode'=>$idperiode))->row_array();
    }

    function get_periodeaktif()
    {
        return $this->db->get_where('periode',array('status'=>'true'))->row_array();
    }
        
    /*
     * Get all periode
     */
    function get_all_periode()
    {
        $this->db->order_by('idperiode', 'desc');
        return $this->db->get('periode')->result_array();
    }
        
    /*
     * function to add new periode
     */
    function add_periode($params)
    {
        $this->db->trans_begin();
        $this->db->where('status', 'true');
        $this->db->update('periode', ['status'=>'false']);
        $this->db->insert('periode',$params);
        $id = $this->db->insert_id();
        if($this->db->trans_status()){
            $this->db->trans_commit();
            return $id;
        }else{
            $this->db->trans_rollback();
            return $params;
        }
    }
    
    /*
     * function to update periode
     */
    function update_periode($idperiode,$params)
    {
        $this->db->where('idperiode',$idperiode);
        return $this->db->update('periode',$params);
    }
    
    /*
     * function to delete periode
     */
    function delete_periode($idperiode)
    {
        return $this->db->delete('periode',array('idperiode'=>$idperiode));
    }
}
