<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get role by idrole
     */
    function get_role($idrole)
    {
        return $this->db->get_where('role',array('idrole'=>$idrole))->row_array();
    }
        
    /*
     * Get all role
     */
    function get_all_role()
    {
        $this->db->order_by('idrole', 'desc');
        return $this->db->get('role')->result_array();
    }
        
    /*
     * function to add new role
     */
    function add_role($params)
    {
        $this->db->insert('role',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update role
     */
    function update_role($idrole,$params)
    {
        $this->db->where('idrole',$idrole);
        return $this->db->update('role',$params);
    }
    
    /*
     * function to delete role
     */
    function delete_role($idrole)
    {
        return $this->db->delete('role',array('idrole'=>$idrole));
    }
}
