<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Userinrole_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get userinrole by iduserinrole
     */
    function get_userinrole($iduserinrole)
    {
        return $this->db->get_where('userinrole',array('iduserinrole'=>$iduserinrole))->row_array();
    }
        
    /*
     * Get all userinrole
     */
    function get_all_userinrole()
    {
        $this->db->order_by('iduserinrole', 'desc');
        return $this->db->get('userinrole')->result_array();
    }
        
    /*
     * function to add new userinrole
     */
    function add_userinrole($params)
    {
        $this->db->insert('userinrole',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update userinrole
     */
    function update_userinrole($iduserinrole,$params)
    {
        $this->db->where('iduserinrole',$iduserinrole);
        return $this->db->update('userinrole',$params);
    }
    
    /*
     * function to delete userinrole
     */
    function delete_userinrole($iduserinrole)
    {
        return $this->db->delete('userinrole',array('iduserinrole'=>$iduserinrole));
    }
}
